# Generated by Django 3.0.8 on 2020-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_auto_20200823_2205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
